title: Streamline
description: CMPT362 Group 4 Project Streamline

header: Streamline
subheader: CMPT362 Group 4

github: CMPT362-Group4/Streamline
apk_link: 

app_description: Streamline is your personalized hub for all things entertainment. Tailored for enthusiasts who value simplicity and efficiency, Streamline empowers you to curate your favorite content effortlessly and share your interests with friends. Seamlessly organize your favorite movies, TV shows, and games in one place, making it easier than ever to keep track of your interests.
